version: "3.9"
services:
  test:
    platform: linux/arm64
    build:
      context: ..
      dockerfile: devops-tooling/ci/Dockerfile
      args:
        ENDPOINT_HOST: localstack
    command: ["${CI_TEST_NAME}.sh"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../auto_tests:/multi-iac-devops/auto_tests
      - ../devops-tooling:/multi-iac-devops/devops-tooling
      - ../iac:/multi-iac-devops/iac
      - ../makefile:/multi-iac-devops/makefile
      - ../run-lambdas.sh:/multi-iac-devops/run-lambdas.sh
      - ../src:/multi-iac-devops/src
    depends_on:
      - localstack
    network_mode: "service:localstack"
