version: "3.9"
services:
  test:
    platform: linux/arm64
    build:
      context: ..
      dockerfile: devops-tooling/ci/Dockerfile
      args:
        ENDPOINT_HOST: localstack
    command: ["${CI_TEST_NAME}.sh"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/multi-iac-devops
    depends_on:
      - localstack
    networks:
      - localstack_network
