version: "3.9"
services:
  test:
    platform: linux/arm64
    build:
      context: ..
      dockerfile: devops-tooling/ci/Dockerfile
    environment:
      - MAPPING_DIR_NAME=${MAPPING_DIR_NAME}
      - CI_TEST_NAME=${CI_TEST_NAME}
      - IS_INTEGRATION=true
      - ARCHITECTURE=${ARCHITECTURE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../auto_tests:${MAPPING_DIR_NAME}/auto_tests
      - ../devops-tooling:${MAPPING_DIR_NAME}/devops-tooling
      - ../iac:${MAPPING_DIR_NAME}/iac
      - ../makefile:${MAPPING_DIR_NAME}/makefile
      - ../run-lambdas.sh:${MAPPING_DIR_NAME}/run-lambdas.sh
      - ../src:${MAPPING_DIR_NAME}/src
    depends_on:
      - localhost.localstack.cloud
    network_mode: "service:localhost.localstack.cloud"
