ARG VERSION
ARG ARCH
FROM public.ecr.aws/lambda/nodejs:${VERSION}

ENV HOME_DIR=/usr/local/layer

RUN --mount=type=cache,target=/var/cache/yum \
    yum makecache && \
    yum update && yum install zip -y \

RUN mkdir -p ${HOME_DIR}
WORKDIR ${HOME_DIR}

COPY package.json .

RUN mkdir -p ./nodejs/node${VERSION}/
RUN npm install
RUN mv node_modules ./nodejs/node${VERSION}

RUN zip -rq layer.zip ./nodejs
