name: Weekly CDK and Terraform Test

on:
  schedule:
    - cron: '0 9 * * 1'  # Run every Monday at 9:00 UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        test_name: [awscdk, awscdktf]
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Install prerequisites
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Load cached Docker images
    - name: Load cached Docker images
      id: load_cache
      uses: actions/cache@v2
      with:
        path: /tmp/docker-images
        key: docker-images-${{ hashFiles('**/Dockerfile') }}

    - name: Load Docker images from cache
      run: |
        if [ -d "/tmp/docker-images" ]; then
          docker load < /tmp/docker-images/images.tar
        fi

    # Start Localstack
    - name: Test
      env:
        LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
        CI_TEST_NAME: ${{ matrix.test_name }}
      run: |
        # Unset stale org secret
        printenv
        unset LOCALSTACK_API_KEY

        echo "Starting Localstack and running tests"
        make run-ci-test

    # Save Docker images to cache
    - name: Save Docker images to cache
      if: steps.load_cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p /tmp/docker-images
        docker save $(docker images -q) > /tmp/docker-images/images.tar
