name: Weekly CDK and Terraform Test

on:
  schedule:
    - cron: '0 9 * * 1'  # Run every Monday at 9:00 UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
env:
  LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    # Only run one test at a time because it seems to be much faster.
    # Possible reason: lots of memory swapping.
    concurrency: 1
    strategy:
      matrix:
        test_name: [ awscdk, awscdktf ]
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Install prerequisites
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Start Localstack
      - name: Test
        env:
          CI_TEST_NAME: ${{ matrix.test_name }}
        run: |
          # Unset stale org secret
          printenv
          unset LOCALSTACK_API_KEY
          
          echo "Starting Localstack and running tests"
          make run-ci-test

  cloudfront-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install prerequisites
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Start Localstack
      - name: Test React app on Cloudfront with Localstack
        run: |
          # Unset stale org secret
          printenv
          unset LOCALSTACK_API_KEY
          
          echo "Starting Localstack and running tests"
          make start-localstack
          make local-tf-cfs3-init
          make local-tf-cfs3-plan
          make local-tf-cfs3-apply
          make local-tf-cfs3-output
          make local-tf-cfs3-test